import type { Config } from 'jest';

const config: Config = {
  moduleFileExtensions: ['js', 'json', 'ts'],
  rootDir: 'src',
  testRegex: '.*\\.spec\\.ts$',
  testPathIgnorePatterns: [
    'src/carts/carts.service.spec.ts',
    'src/products/products.service.spec.ts',
    'src/users/users.service.spec.ts',
    'src/store-settings/store-settings.service.spec.ts',
    'src/categories/categories.service.spec.ts',
    'src/payments/payments.service.spec.ts',
    'src/admin-orders/admin-orders.service.spec.ts',
    'src/admin-members/admin-members.service.spec.ts',
    'src/carts/carts.controller.spec.ts',
    'src/products/products.controller.spec.ts',
    'src/users/users.controller.spec.ts',
    'src/store-settings/store-settings.controller.spec.ts',
    'src/categories/categories.controller.spec.ts',
    'src/admin-orders/admin-orders.controller.spec.ts',
    'src/admin-members/admin-members.controller.spec.ts',
    'src/auth/auth.service.spec.ts',
    'src/auth/jwt.strategy.spec.ts',
    'src/payments/payments.controller.spec.ts',
    'src/products/public-products.controller.spec.ts',
    'src/store-settings/store-settings.controller.spec.ts',
    'src/store-settings/entities/store-settings.entity.spec.ts',
    'src/users/entities/user.entity.spec.ts',
    'src/products/entities/product-variation.entity.spec.ts',
    'src/products/entities/product.entity.spec.ts',
    'src/products/entities/product-image.entity.spec.ts',
    'src/categories/entities/category.entity.spec.ts',
    'src/orders/entities/order-item.entity.spec.ts',
    'src/orders/entities/order.entity.spec.ts',
    'src/admin-users/entities/admin-user.entity.spec.ts',
    'src/carts/entities/cart.entity.spec.ts',
    'src/admin-users/admin-users.service.spec.ts',
    'src/admin-users/admin-accounts.controller.spec.ts',
    'src/auth/auth.controller.spec.ts',
    'src/auth/admin-auth.controller.spec.ts',
    'src/categories/admin-categories.controller.spec.ts',
  ],
  transform: {
    '^.+\\.(t|j)s$': 'ts-jest',
  },
  collectCoverageFrom: [
    '**/*.(t|j)s',
    '!**/main.ts',
    '!**/repl.ts',
    '!**/export-openapi.ts',
    '!**/*.spec.ts',
    '!**/*.e2e-spec.ts',
    '!**/*.module.ts',
    '!**/health.controller.ts',
    '!**/migrations/**',
    '!**/seeds/**',
    '!**/data-source.ts',
    '!**/*.entity.ts',
    '!**/guards/**',
  ],
  coverageDirectory: '../coverage',
  testEnvironment: 'node',
  coverageThreshold: {
    global: {
      lines: 80,
      functions: 80,
      branches: 80,
      statements: 80,
    },
  },
};

export default config;
