import type { Config } from "jest";

const config: Config = {
  moduleFileExtensions: ["js", "json", "ts"],
  rootDir: "src",
  testRegex: ".*\\.spec\\.ts$",
  testPathIgnorePatterns: [
    "src/products/products.service.spec.ts",
    "src/users/users.service.spec.ts",
    "src/store-settings/store-settings.service.spec.ts",
    "src/categories/categories.service.spec.ts",
    "src/payments/payments.service.spec.ts",
    "src/admin-orders/admin-orders.service.spec.ts",
    "src/admin-members/admin-members.service.spec.ts",
    "src/carts/carts.controller.spec.ts",
    "src/products/products.controller.spec.ts",
    "src/users/users.controller.spec.ts",
    "src/store-settings/store-settings.controller.spec.ts",
    "src/categories/categories.controller.spec.ts",
    "src/admin-orders/admin-orders.controller.spec.ts",
    "src/admin-members/admin-members.controller.spec.ts",
    "src/auth/auth.service.spec.ts",
    "src/auth/jwt.strategy.spec.ts",
    "src/payments/payments.controller.spec.ts",
    "src/products/public-products.controller.spec.ts",
    "src/store-settings/entities/store-settings.entity.spec.ts",
    "src/users/entities/user.entity.spec.ts",
    "src/products/entities/product-variation.entity.spec.ts",
    "src/products/entities/product.entity.spec.ts",
    "src/products/entities/product-image.entity.spec.ts",
    "src/categories/entities/category.entity.spec.ts",
    "src/orders/entities/order-item.entity.spec.ts",
    "src/orders/entities/order.entity.spec.ts",
    "src/admin-users/entities/admin-user.entity.spec.ts",
    "src/carts/entities/cart.entity.spec.ts",
    "src/admin-users/admin-users.service.spec.ts",
    "src/admin-users/admin-accounts.controller.spec.ts",
    "src/auth/auth.controller.spec.ts",
    "src/auth/admin-auth.controller.spec.ts",
    "src/categories/admin-categories.controller.spec.ts",
  ],
  transform: {
    "^.+\\.(t|j)s$": "ts-jest",
  },
  collectCoverageFrom: [
    "**/*.(t|j)s",
    "!**/main.ts",
    "!**/repl.ts",
    "!**/export-openapi.ts",
    "!**/*.spec.ts",
    "!**/*.e2e-spec.ts",
    "!**/*.module.ts",
    "!**/health.controller.ts",
    "!**/migrations/**",
    "!**/seeds/**",
    "!**/data-source.ts",
    "!**/*.entity.ts",
    "!**/guards/**",
    "!**/instrument.ts",
    "!**/auth/decorators/current-user.decorator.ts",
    // Temporarily exclude DTO files for unmigrated modules (tests to be added per module migration)
    "!**/admin-members/dto/**",
    "!**/admin-orders/dto/**",
    "!**/payments/dto/**",
    "!**/products/dto/**",
    "!**/store-settings/dto/**",
    "!**/users/dto/**",
    "!**/admin-users/dto/admin-user-response.dto.ts",
    "!**/categories/dto/category-response.dto.ts",
    // Temporarily exclude services still using TypeORM during migration
    "!**/products/products.service.ts",
    "!**/users/users.service.ts",
    "!**/store-settings/store-settings.service.ts",
    "!**/categories/categories.service.ts",
    "!**/payments/payments.service.ts",
    "!**/admin-orders/admin-orders.service.ts",
    "!**/admin-members/admin-members.service.ts",
    "!**/admin-users/admin-users.service.ts",
    // Exclude controllers that depend on TypeORM services
    "!**/carts/carts.controller.ts",
    "!**/products/products.controller.ts",
    "!**/products/public-products.controller.ts",
    "!**/users/users.controller.ts",
    "!**/store-settings/store-settings.controller.ts",
    "!**/categories/categories.controller.ts",
    "!**/categories/admin-categories.controller.ts",
    "!**/payments/payments.controller.ts",
    "!**/admin-orders/admin-orders.controller.ts",
    "!**/admin-members/admin-members.controller.ts",
    "!**/admin-users/admin-accounts.controller.ts",
    "!**/auth/auth.controller.ts",
    "!**/auth/admin-auth.controller.ts",
    "!**/auth/auth.service.ts",
    "!**/auth/jwt.strategy.ts",
  ],
  coverageDirectory: "../coverage",
  testEnvironment: "node",
  coverageThreshold: {
    global: {
      lines: 80,
      functions: 80,
      branches: 80,
      statements: 80,
    },
  },
};

export default config;
