/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AuthenticatedMyPageRouteImport } from './routes/_authenticated/my-page'
import { Route as AuthenticatedCartRouteImport } from './routes/_authenticated/cart'
import { Route as AdminAdminRouteImport } from './routes/_admin.admin'
import { Route as AuthenticatedProductsIndexRouteImport } from './routes/_authenticated/products/index'
import { Route as AuthenticatedCheckoutIndexRouteImport } from './routes/_authenticated/checkout/index'
import { Route as AdminAdminIndexRouteImport } from './routes/_admin.admin.index'
import { Route as AuthenticatedProductsProductIdRouteImport } from './routes/_authenticated/products/$productId'
import { Route as AuthenticatedCheckoutCompleteRouteImport } from './routes/_authenticated/checkout/complete'
import { Route as AdminAdminSettingsRouteImport } from './routes/_admin.admin.settings'
import { Route as AdminAdminProductsRouteImport } from './routes/_admin.admin.products'
import { Route as AdminAdminOrdersRouteImport } from './routes/_admin.admin.orders'
import { Route as AdminAdminMembersRouteImport } from './routes/_admin.admin.members'
import { Route as AdminAdminCategoriesRouteImport } from './routes/_admin.admin.categories'
import { Route as AdminAdminAdminsRouteImport } from './routes/_admin.admin.admins'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMyPageRoute = AuthenticatedMyPageRouteImport.update({
  id: '/my-page',
  path: '/my-page',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCartRoute = AuthenticatedCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AdminAdminRoute = AdminAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AdminRoute,
} as any)
const AuthenticatedProductsIndexRoute =
  AuthenticatedProductsIndexRouteImport.update({
    id: '/products/',
    path: '/products/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCheckoutIndexRoute =
  AuthenticatedCheckoutIndexRouteImport.update({
    id: '/checkout/',
    path: '/checkout/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AdminAdminIndexRoute = AdminAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AuthenticatedProductsProductIdRoute =
  AuthenticatedProductsProductIdRouteImport.update({
    id: '/products/$productId',
    path: '/products/$productId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCheckoutCompleteRoute =
  AuthenticatedCheckoutCompleteRouteImport.update({
    id: '/checkout/complete',
    path: '/checkout/complete',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AdminAdminSettingsRoute = AdminAdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminProductsRoute = AdminAdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminOrdersRoute = AdminAdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminMembersRoute = AdminAdminMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminCategoriesRoute = AdminAdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminAdminsRoute = AdminAdminAdminsRouteImport.update({
  id: '/admins',
  path: '/admins',
  getParentRoute: () => AdminAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin': typeof AdminAdminRouteWithChildren
  '/cart': typeof AuthenticatedCartRoute
  '/my-page': typeof AuthenticatedMyPageRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/admins': typeof AdminAdminAdminsRoute
  '/admin/categories': typeof AdminAdminCategoriesRoute
  '/admin/members': typeof AdminAdminMembersRoute
  '/admin/orders': typeof AdminAdminOrdersRoute
  '/admin/products': typeof AdminAdminProductsRoute
  '/admin/settings': typeof AdminAdminSettingsRoute
  '/checkout/complete': typeof AuthenticatedCheckoutCompleteRoute
  '/products/$productId': typeof AuthenticatedProductsProductIdRoute
  '/admin/': typeof AdminAdminIndexRoute
  '/checkout/': typeof AuthenticatedCheckoutIndexRoute
  '/products/': typeof AuthenticatedProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/cart': typeof AuthenticatedCartRoute
  '/my-page': typeof AuthenticatedMyPageRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/admins': typeof AdminAdminAdminsRoute
  '/admin/categories': typeof AdminAdminCategoriesRoute
  '/admin/members': typeof AdminAdminMembersRoute
  '/admin/orders': typeof AdminAdminOrdersRoute
  '/admin/products': typeof AdminAdminProductsRoute
  '/admin/settings': typeof AdminAdminSettingsRoute
  '/checkout/complete': typeof AuthenticatedCheckoutCompleteRoute
  '/products/$productId': typeof AuthenticatedProductsProductIdRoute
  '/admin': typeof AdminAdminIndexRoute
  '/checkout': typeof AuthenticatedCheckoutIndexRoute
  '/products': typeof AuthenticatedProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_admin': typeof AdminRouteWithChildren
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_admin/admin': typeof AdminAdminRouteWithChildren
  '/_authenticated/cart': typeof AuthenticatedCartRoute
  '/_authenticated/my-page': typeof AuthenticatedMyPageRoute
  '/admin/login': typeof AdminLoginRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_admin/admin/admins': typeof AdminAdminAdminsRoute
  '/_admin/admin/categories': typeof AdminAdminCategoriesRoute
  '/_admin/admin/members': typeof AdminAdminMembersRoute
  '/_admin/admin/orders': typeof AdminAdminOrdersRoute
  '/_admin/admin/products': typeof AdminAdminProductsRoute
  '/_admin/admin/settings': typeof AdminAdminSettingsRoute
  '/_authenticated/checkout/complete': typeof AuthenticatedCheckoutCompleteRoute
  '/_authenticated/products/$productId': typeof AuthenticatedProductsProductIdRoute
  '/_admin/admin/': typeof AdminAdminIndexRoute
  '/_authenticated/checkout/': typeof AuthenticatedCheckoutIndexRoute
  '/_authenticated/products/': typeof AuthenticatedProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/admin'
    | '/cart'
    | '/my-page'
    | '/admin/login'
    | '/admin/admins'
    | '/admin/categories'
    | '/admin/members'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/settings'
    | '/checkout/complete'
    | '/products/$productId'
    | '/admin/'
    | '/checkout/'
    | '/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/cart'
    | '/my-page'
    | '/admin/login'
    | '/admin/admins'
    | '/admin/categories'
    | '/admin/members'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/settings'
    | '/checkout/complete'
    | '/products/$productId'
    | '/admin'
    | '/checkout'
    | '/products'
  id:
    | '__root__'
    | '/_admin'
    | '/_authenticated'
    | '/login'
    | '/register'
    | '/_admin/admin'
    | '/_authenticated/cart'
    | '/_authenticated/my-page'
    | '/admin/login'
    | '/_authenticated/'
    | '/_admin/admin/admins'
    | '/_admin/admin/categories'
    | '/_admin/admin/members'
    | '/_admin/admin/orders'
    | '/_admin/admin/products'
    | '/_admin/admin/settings'
    | '/_authenticated/checkout/complete'
    | '/_authenticated/products/$productId'
    | '/_admin/admin/'
    | '/_authenticated/checkout/'
    | '/_authenticated/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AdminRoute: typeof AdminRouteWithChildren
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  AdminLoginRoute: typeof AdminLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/my-page': {
      id: '/_authenticated/my-page'
      path: '/my-page'
      fullPath: '/my-page'
      preLoaderRoute: typeof AuthenticatedMyPageRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cart': {
      id: '/_authenticated/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof AuthenticatedCartRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_admin/admin': {
      id: '/_admin/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminAdminRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_authenticated/products/': {
      id: '/_authenticated/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof AuthenticatedProductsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/checkout/': {
      id: '/_authenticated/checkout/'
      path: '/checkout'
      fullPath: '/checkout/'
      preLoaderRoute: typeof AuthenticatedCheckoutIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_admin/admin/': {
      id: '/_admin/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminAdminIndexRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_authenticated/products/$productId': {
      id: '/_authenticated/products/$productId'
      path: '/products/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof AuthenticatedProductsProductIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/checkout/complete': {
      id: '/_authenticated/checkout/complete'
      path: '/checkout/complete'
      fullPath: '/checkout/complete'
      preLoaderRoute: typeof AuthenticatedCheckoutCompleteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_admin/admin/settings': {
      id: '/_admin/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminAdminSettingsRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/products': {
      id: '/_admin/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminAdminProductsRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/orders': {
      id: '/_admin/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminAdminOrdersRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/members': {
      id: '/_admin/admin/members'
      path: '/members'
      fullPath: '/admin/members'
      preLoaderRoute: typeof AdminAdminMembersRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/categories': {
      id: '/_admin/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminAdminCategoriesRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/admins': {
      id: '/_admin/admin/admins'
      path: '/admins'
      fullPath: '/admin/admins'
      preLoaderRoute: typeof AdminAdminAdminsRouteImport
      parentRoute: typeof AdminAdminRoute
    }
  }
}

interface AdminAdminRouteChildren {
  AdminAdminAdminsRoute: typeof AdminAdminAdminsRoute
  AdminAdminCategoriesRoute: typeof AdminAdminCategoriesRoute
  AdminAdminMembersRoute: typeof AdminAdminMembersRoute
  AdminAdminOrdersRoute: typeof AdminAdminOrdersRoute
  AdminAdminProductsRoute: typeof AdminAdminProductsRoute
  AdminAdminSettingsRoute: typeof AdminAdminSettingsRoute
  AdminAdminIndexRoute: typeof AdminAdminIndexRoute
}

const AdminAdminRouteChildren: AdminAdminRouteChildren = {
  AdminAdminAdminsRoute: AdminAdminAdminsRoute,
  AdminAdminCategoriesRoute: AdminAdminCategoriesRoute,
  AdminAdminMembersRoute: AdminAdminMembersRoute,
  AdminAdminOrdersRoute: AdminAdminOrdersRoute,
  AdminAdminProductsRoute: AdminAdminProductsRoute,
  AdminAdminSettingsRoute: AdminAdminSettingsRoute,
  AdminAdminIndexRoute: AdminAdminIndexRoute,
}

const AdminAdminRouteWithChildren = AdminAdminRoute._addFileChildren(
  AdminAdminRouteChildren,
)

interface AdminRouteChildren {
  AdminAdminRoute: typeof AdminAdminRouteWithChildren
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminRoute: AdminAdminRouteWithChildren,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedCartRoute: typeof AuthenticatedCartRoute
  AuthenticatedMyPageRoute: typeof AuthenticatedMyPageRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedCheckoutCompleteRoute: typeof AuthenticatedCheckoutCompleteRoute
  AuthenticatedProductsProductIdRoute: typeof AuthenticatedProductsProductIdRoute
  AuthenticatedCheckoutIndexRoute: typeof AuthenticatedCheckoutIndexRoute
  AuthenticatedProductsIndexRoute: typeof AuthenticatedProductsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedCartRoute: AuthenticatedCartRoute,
  AuthenticatedMyPageRoute: AuthenticatedMyPageRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedCheckoutCompleteRoute: AuthenticatedCheckoutCompleteRoute,
  AuthenticatedProductsProductIdRoute: AuthenticatedProductsProductIdRoute,
  AuthenticatedCheckoutIndexRoute: AuthenticatedCheckoutIndexRoute,
  AuthenticatedProductsIndexRoute: AuthenticatedProductsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AdminRoute: AdminRouteWithChildren,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  AdminLoginRoute: AdminLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
